// Secrets set via `wrangler secret put` — not generated by `wrangler types`
// Variables set in wrangler.jsonc `vars` are generated by `wrangler types` instead
// Declared in Cloudflare.Env so they are visible on `env` imported from `cloudflare:workers`
declare namespace Cloudflare {
    interface Env {
        GITHUB_CLIENT_ID: string;
        GITHUB_CLIENT_SECRET: string;
        COOKIE_ENCRYPTION_KEY: string;
        ALLOWED_USERNAMES: string;
        STORAGE_ENCRYPTION_KEY: string;
        DATA_REPO_OWNER: string;
        USER_TIMEZONE: string;
        USER_LOCALE: string;
    }
}
